---
dbtVersion: 0.18.1
jobs:
- name: Daily Marketing
  schedule: 0 */12 * * *
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run asana
    command: dbt run --models asana
  - name: run hubspot
    command: dbt run --models hubspot
